version: '3.8'
services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: >
      agent -server -ui
      -node=server-1
      -bootstrap-expect=1
      -client=0.0.0.0
      -config-file=/consul-acl.json
    volumes:
      - ./config:/config
      - consul_data:/consul/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"

volumes:
  consul_data:
  jenkins_home:
